//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adfnet.Core.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adfnet.Core.Globalization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlişkili kayıt silinemez!.
        /// </summary>
        public static string DangerAssociatedRecordNotDeleted {
            get {
                return ResourceManager.GetString("DangerAssociatedRecordNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut veritabanı kaldırılamadı!.
        /// </summary>
        public static string DangerExistingDatabaseNotRemoved {
            get {
                return ResourceManager.GetString("DangerExistingDatabaseNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} daha önce kullanılmış!.
        /// </summary>
        public static string DangerFieldDuplicated {
            get {
                return ResourceManager.GetString("DangerFieldDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı boş bırakılamaz!.
        /// </summary>
        public static string DangerFieldIsEmpty {
            get {
                return ResourceManager.GetString("DangerFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı {1} karakterden az girilmiş!.
        /// </summary>
        public static string DangerFieldLengthLimit {
            get {
                return ResourceManager.GetString("DangerFieldLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik bilgileri bulunamadı!.
        /// </summary>
        public static string DangerIdentityUserNotFound {
            get {
                return ResourceManager.GetString("DangerIdentityUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifre hatalı!.
        /// </summary>
        public static string DangerIncorrectOldPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı şifre!.
        /// </summary>
        public static string DangerIncorrectPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api client yetkili değil!.
        /// </summary>
        public static string DangerInvalidApiClient {
            get {
                return ResourceManager.GetString("DangerInvalidApiClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresi geçerli değil!.
        /// </summary>
        public static string DangerInvalidEmail {
            get {
                return ResourceManager.GetString("DangerInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik geçerli değil!.
        /// </summary>
        public static string DangerInvalidEntitiy {
            get {
                return ResourceManager.GetString("DangerInvalidEntitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yeterince karmaşık değil!.
        /// </summary>
        public static string DangerInvalidPassword {
            get {
                return ResourceManager.GetString("DangerInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili kayıt onaylı değil!.
        /// </summary>
        public static string DangerItemNotApproved {
            get {
                return ResourceManager.GetString("DangerItemNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni veritabanı oluşturulamadı!.
        /// </summary>
        public static string DangerNewDatabaseNotCreated {
            get {
                return ResourceManager.GetString("DangerNewDatabaseNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem için yetkiniz yok!.
        /// </summary>
        public static string DangerNoPermission {
            get {
                return ResourceManager.GetString("DangerNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst kayıt bulunamadı!.
        /// </summary>
        public static string DangerParentNotFound {
            get {
                return ResourceManager.GetString("DangerParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler aynı değil!.
        /// </summary>
        public static string DangerPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("DangerPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        public static string DangerRecordNotFound {
            get {
                return ResourceManager.GetString("DangerRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfada kayıt bulunamadı!.
        /// </summary>
        public static string DangerRecordNotFoundInPage {
            get {
                return ResourceManager.GetString("DangerRecordNotFoundInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıya tanımlı bir rol bulunamadı!.
        /// </summary>
        public static string DangerUserHasNoRole {
            get {
                return ResourceManager.GetString("DangerUserHasNoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı!.
        /// </summary>
        public static string DangerUserNotFound {
            get {
                return ResourceManager.GetString("DangerUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencereyi kapatabilirsiniz..
        /// </summary>
        public static string InfoCanCloseWindow {
            get {
                return ResourceManager.GetString("InfoCanCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi başarıyla tamamlandı..
        /// </summary>
        public static string InfoDeletionOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoDeletionOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut veritabanı kaldırıldı..
        /// </summary>
        public static string InfoExistingDatabaseRemoved {
            get {
                return ResourceManager.GetString("InfoExistingDatabaseRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut veritabanı kaldırılıyor....
        /// </summary>
        public static string InfoExistingDatabaseRemoving {
            get {
                return ResourceManager.GetString("InfoExistingDatabaseRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla giriş yapıldı..
        /// </summary>
        public static string InfoLoginOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoLoginOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla çıkış yapıldı..
        /// </summary>
        public static string InfoLogoutOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoLogoutOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni veritabanı oluşturuldu..
        /// </summary>
        public static string InfoNewDatabaseCreated {
            get {
                return ResourceManager.GetString("InfoNewDatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni veritabanı oluşturuluyor....
        /// </summary>
        public static string InfoNewDatabaseCreating {
            get {
                return ResourceManager.GetString("InfoNewDatabaseCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre başarıyla gönderildi..
        /// </summary>
        public static string InfoPasswordSentSuccesfully {
            get {
                return ResourceManager.GetString("InfoPasswordSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum başlatılıyor....
        /// </summary>
        public static string InfoStartingInstallation {
            get {
                return ResourceManager.GetString("InfoStartingInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aranacak kelimeyi yazınız....
        /// </summary>
        public static string InfoTypeSearchedWord {
            get {
                return ResourceManager.GetString("InfoTypeSearchedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSure {
            get {
                return ResourceManager.GetString("QuestionAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureDelete {
            get {
                return ResourceManager.GetString("QuestionAreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu sonlandırmak istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureLogout {
            get {
                return ResourceManager.GetString("QuestionAreYouSureLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Tamamlandı..
        /// </summary>
        public static string SuccessInstallationOk {
            get {
                return ResourceManager.GetString("SuccessInstallationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tamamlandı..
        /// </summary>
        public static string SuccessItemOk {
            get {
                return ResourceManager.GetString("SuccessItemOk", resourceCulture);
            }
        }
    }
}
